//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by flag.rc
//
#define IDI_COUNTRY_FLAG_AD             101
#define IDI_COUNTRY_FLAG_AE             102
#define IDI_COUNTRY_FLAG_AF             103
#define IDI_COUNTRY_FLAG_AG             104
#define IDI_COUNTRY_FLAG_AI             105
#define IDI_COUNTRY_FLAG_AL             106
#define IDI_COUNTRY_FLAG_AM             107
#define IDI_COUNTRY_FLAG_AN             108
#define IDI_COUNTRY_FLAG_AO             109
#define IDI_COUNTRY_FLAG_AR             110
#define IDI_COUNTRY_FLAG_AS             111
#define IDI_COUNTRY_FLAG_AT             112
#define IDI_COUNTRY_FLAG_AU             113
#define IDI_COUNTRY_FLAG_AW             114
#define IDI_COUNTRY_FLAG_AZ             115
#define IDI_COUNTRY_FLAG_BA             116
#define IDI_COUNTRY_FLAG_BB             117
#define IDI_COUNTRY_FLAG_BD             118
#define IDI_COUNTRY_FLAG_BE             119
#define IDI_COUNTRY_FLAG_BF             120
#define IDI_COUNTRY_FLAG_BG             121
#define IDI_COUNTRY_FLAG_BH             122
#define IDI_COUNTRY_FLAG_BI             123
#define IDI_COUNTRY_FLAG_BJ             124
#define IDI_COUNTRY_FLAG_BM             125
#define IDI_COUNTRY_FLAG_BN             126
#define IDI_COUNTRY_FLAG_BO             127
#define IDI_COUNTRY_FLAG_BR             128
#define IDI_COUNTRY_FLAG_BS             129
#define IDI_COUNTRY_FLAG_BT             130
#define IDI_COUNTRY_FLAG_BW             131
#define IDI_COUNTRY_FLAG_BY             132
#define IDI_COUNTRY_FLAG_BZ             133
#define IDI_COUNTRY_FLAG_CA             134
#define IDI_COUNTRY_FLAG_CC             135
#define IDI_COUNTRY_FLAG_CD             136
#define IDI_COUNTRY_FLAG_CF             137
#define IDI_COUNTRY_FLAG_CG             138
#define IDI_COUNTRY_FLAG_CH             139
#define IDI_COUNTRY_FLAG_CI             140
#define IDI_COUNTRY_FLAG_CK             141
#define IDI_COUNTRY_FLAG_CL             142
#define IDI_COUNTRY_FLAG_CM             143
#define IDI_COUNTRY_FLAG_CN             144
#define IDI_COUNTRY_FLAG_CO             145
#define IDI_COUNTRY_FLAG_CR             146
#define IDI_COUNTRY_FLAG_CU             147
#define IDI_COUNTRY_FLAG_CV             148
#define IDI_COUNTRY_FLAG_CX             149
#define IDI_COUNTRY_FLAG_CY             150
#define IDI_COUNTRY_FLAG_CZ             151
#define IDI_COUNTRY_FLAG_DE             152
#define IDI_COUNTRY_FLAG_DJ             153
#define IDI_COUNTRY_FLAG_DK             154
#define IDI_COUNTRY_FLAG_DM             155
#define IDI_COUNTRY_FLAG_DO             156
#define IDI_COUNTRY_FLAG_DZ             157
#define IDI_COUNTRY_FLAG_EC             158
#define IDI_COUNTRY_FLAG_EE             159
#define IDI_COUNTRY_FLAG_EG             160
#define IDI_COUNTRY_FLAG_EH             161
#define IDI_COUNTRY_FLAG_ER             162
#define IDI_COUNTRY_FLAG_ES             163
#define IDI_COUNTRY_FLAG_ET             164
#define IDI_COUNTRY_FLAG_FI             165
#define IDI_COUNTRY_FLAG_FJ             166
#define IDI_COUNTRY_FLAG_FK             167
#define IDI_COUNTRY_FLAG_FM             168
#define IDI_COUNTRY_FLAG_FO             169
#define IDI_COUNTRY_FLAG_FR             170
#define IDI_COUNTRY_FLAG_GA             171
#define IDI_COUNTRY_FLAG_GB             172
#define IDI_COUNTRY_FLAG_GD             173
#define IDI_COUNTRY_FLAG_GE             174
#define IDI_COUNTRY_FLAG_GG             175
#define IDI_COUNTRY_FLAG_GH             176
#define IDI_COUNTRY_FLAG_GI             177
#define IDI_COUNTRY_FLAG_GK             178
#define IDI_COUNTRY_FLAG_GL             179
#define IDI_COUNTRY_FLAG_GM             180
#define IDI_COUNTRY_FLAG_GN             181
#define IDI_COUNTRY_FLAG_GP             182
#define IDI_COUNTRY_FLAG_GQ             183
#define IDI_COUNTRY_FLAG_GR             184
#define IDI_COUNTRY_FLAG_GS             185
#define IDI_COUNTRY_FLAG_GT             186
#define IDI_COUNTRY_FLAG_GU             187
#define IDI_COUNTRY_FLAG_GW             188
#define IDI_COUNTRY_FLAG_GY             189
#define IDI_COUNTRY_FLAG_HK             190
#define IDI_COUNTRY_FLAG_HN             191
#define IDI_COUNTRY_FLAG_HR             192
#define IDI_COUNTRY_FLAG_HT             193
#define IDI_COUNTRY_FLAG_HU             194
#define IDI_COUNTRY_FLAG_ID             195
#define IDI_COUNTRY_FLAG_IE             196
#define IDI_COUNTRY_FLAG_IL             197
#define IDI_COUNTRY_FLAG_IM             198
#define IDI_COUNTRY_FLAG_IN             199
#define IDI_COUNTRY_FLAG_IO             200
#define IDI_COUNTRY_FLAG_IQ             201
#define IDI_COUNTRY_FLAG_IR             202
#define IDI_COUNTRY_FLAG_IS             203
#define IDI_COUNTRY_FLAG_IT             204
#define IDI_COUNTRY_FLAG_JE             205
#define IDI_COUNTRY_FLAG_JM             206
#define IDI_COUNTRY_FLAG_JO             207
#define IDI_COUNTRY_FLAG_JP             208
#define IDI_COUNTRY_FLAG_KE             209
#define IDI_COUNTRY_FLAG_KG             210
#define IDI_COUNTRY_FLAG_KH             211
#define IDI_COUNTRY_FLAG_KI             212
#define IDI_COUNTRY_FLAG_KM             213
#define IDI_COUNTRY_FLAG_KN             214
#define IDI_COUNTRY_FLAG_KP             215
#define IDI_COUNTRY_FLAG_KR             216
#define IDI_COUNTRY_FLAG_KW             217
#define IDI_COUNTRY_FLAG_KY             218
#define IDI_COUNTRY_FLAG_KZ             219
#define IDI_COUNTRY_FLAG_LA             220
#define IDI_COUNTRY_FLAG_LB             221
#define IDI_COUNTRY_FLAG_LC             222
#define IDI_COUNTRY_FLAG_LI             223
#define IDI_COUNTRY_FLAG_LK             224
#define IDI_COUNTRY_FLAG_LR             225
#define IDI_COUNTRY_FLAG_LS             226
#define IDI_COUNTRY_FLAG_LT             227
#define IDI_COUNTRY_FLAG_LU             228
#define IDI_COUNTRY_FLAG_LV             229
#define IDI_COUNTRY_FLAG_LY             230
#define IDI_COUNTRY_FLAG_MA             231
#define IDI_COUNTRY_FLAG_MC             232
#define IDI_COUNTRY_FLAG_MD             233
#define IDI_COUNTRY_FLAG_MG             234
#define IDI_COUNTRY_FLAG_MH             235
#define IDI_COUNTRY_FLAG_MK             236
#define IDI_COUNTRY_FLAG_ML             237
#define IDI_COUNTRY_FLAG_MM             238
#define IDI_COUNTRY_FLAG_MN             239
#define IDI_COUNTRY_FLAG_MO             240
#define IDI_COUNTRY_FLAG_MP             241
#define IDI_COUNTRY_FLAG_MQ             242
#define IDI_COUNTRY_FLAG_MR             243
#define IDI_COUNTRY_FLAG_MS             244
#define IDI_COUNTRY_FLAG_MT             245
#define IDI_COUNTRY_FLAG_MU             246
#define IDI_COUNTRY_FLAG_MV             247
#define IDI_COUNTRY_FLAG_MW             248
#define IDI_COUNTRY_FLAG_MX             249
#define IDI_COUNTRY_FLAG_MY             250
#define IDI_COUNTRY_FLAG_MZ             251
#define IDI_COUNTRY_FLAG_NA             252
#define IDI_COUNTRY_FLAG_NC             253
#define IDI_COUNTRY_FLAG_NE             254
#define IDI_COUNTRY_FLAG_NF             255
#define IDI_COUNTRY_FLAG_NG             256
#define IDI_COUNTRY_FLAG_NI             257
#define IDI_COUNTRY_FLAG_NL             258
#define IDI_COUNTRY_FLAG_NO             259
#define IDI_COUNTRY_FLAG_NP             260
#define IDI_COUNTRY_FLAG_NR             261
#define IDI_COUNTRY_FLAG_NU             262
#define IDI_COUNTRY_FLAG_NZ             263
#define IDI_COUNTRY_FLAG_OM             264
#define IDI_COUNTRY_FLAG_PA             265
#define IDI_COUNTRY_FLAG_PC             266
#define IDI_COUNTRY_FLAG_PE             267
#define IDI_COUNTRY_FLAG_PF             268
#define IDI_COUNTRY_FLAG_PG             269
#define IDI_COUNTRY_FLAG_PH             270
#define IDI_COUNTRY_FLAG_PK             271
#define IDI_COUNTRY_FLAG_PL             272
#define IDI_COUNTRY_FLAG_PM             273
#define IDI_COUNTRY_FLAG_PN             274
#define IDI_COUNTRY_FLAG_PR             275
#define IDI_COUNTRY_FLAG_PS             276
#define IDI_COUNTRY_FLAG_PT             277
#define IDI_COUNTRY_FLAG_PW             278
#define IDI_COUNTRY_FLAG_PY             279
#define IDI_COUNTRY_FLAG_QA             280
#define IDI_COUNTRY_FLAG_RO             281
#define IDI_COUNTRY_FLAG_RU             282
#define IDI_COUNTRY_FLAG_RW             283
#define IDI_COUNTRY_FLAG_SA             284
#define IDI_COUNTRY_FLAG_SB             285
#define IDI_COUNTRY_FLAG_SC             286
#define IDI_COUNTRY_FLAG_SD             287
#define IDI_COUNTRY_FLAG_SE             288
#define IDI_COUNTRY_FLAG_SG             289
#define IDI_COUNTRY_FLAG_SH             290
#define IDI_COUNTRY_FLAG_SI             291
#define IDI_COUNTRY_FLAG_SK             292
#define IDI_COUNTRY_FLAG_SL             293
#define IDI_COUNTRY_FLAG_SM             294
#define IDI_COUNTRY_FLAG_SN             295
#define IDI_COUNTRY_FLAG_SO             296
#define IDI_COUNTRY_FLAG_SR             297
#define IDI_COUNTRY_FLAG_ST             298
#define IDI_COUNTRY_FLAG_SU             299
#define IDI_COUNTRY_FLAG_SV             300
#define IDI_COUNTRY_FLAG_SY             301
#define IDI_COUNTRY_FLAG_SZ             302
#define IDI_COUNTRY_FLAG_TC             303
#define IDI_COUNTRY_FLAG_TD             304
#define IDI_COUNTRY_FLAG_TF             305
#define IDI_COUNTRY_FLAG_TG             306
#define IDI_COUNTRY_FLAG_TH             307
#define IDI_COUNTRY_FLAG_TJ             308
#define IDI_COUNTRY_FLAG_TK             309
#define IDI_COUNTRY_FLAG_TL             310
#define IDI_COUNTRY_FLAG_TM             311
#define IDI_COUNTRY_FLAG_TN             312
#define IDI_COUNTRY_FLAG_TO             313
#define IDI_COUNTRY_FLAG_TR             314
#define IDI_COUNTRY_FLAG_TT             315
#define IDI_COUNTRY_FLAG_TV             316
#define IDI_COUNTRY_FLAG_TW             317
#define IDI_COUNTRY_FLAG_TZ             318
#define IDI_COUNTRY_FLAG_UA             319
#define IDI_COUNTRY_FLAG_UG             320
#define IDI_COUNTRY_FLAG_UM             321
#define IDI_COUNTRY_FLAG_US             322
#define IDI_COUNTRY_FLAG_UY             323
#define IDI_COUNTRY_FLAG_UZ             324
#define IDI_COUNTRY_FLAG_VA             325
#define IDI_COUNTRY_FLAG_VC             326
#define IDI_COUNTRY_FLAG_VE             327
#define IDI_COUNTRY_FLAG_VG             328
#define IDI_COUNTRY_FLAG_VI             329
#define IDI_COUNTRY_FLAG_VN             330
#define IDI_COUNTRY_FLAG_VU             331
#define IDI_COUNTRY_FLAG_WF             332
#define IDI_COUNTRY_FLAG_WS             333
#define IDI_COUNTRY_FLAG_YE             334
#define IDI_COUNTRY_FLAG_YU             335
#define IDI_COUNTRY_FLAG_ZA             336
#define IDI_COUNTRY_FLAG_ZM             337
#define IDI_COUNTRY_FLAG_ZW             338
#define IDI_COUNTRY_FLAG_UK             340
#define IDI_COUNTRY_FLAG_CS             341
#define IDI_COUNTRY_FLAG_TS             342
#define IDI_COUNTRY_FLAG_NOFLAG         343


// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        347
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1001
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
